# Form implementation generated from reading ui file 'Acerca.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Acerca(object):
    def setupUi(self, Acerca):
        Acerca.setObjectName("Acerca")
        Acerca.resize(896, 527)
        Acerca.setStyleSheet("background-color: #FFFAFA;")
        self.label = QtWidgets.QLabel(parent=Acerca)
        self.label.setGeometry(QtCore.QRect(30, 100, 541, 291))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Acerca)
        self.label_2.setGeometry(QtCore.QRect(580, 100, 251, 281))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/acercaAplicacion.png"))
        self.label_2.setObjectName("label_2")
        self.btnSalirAcerca = QtWidgets.QPushButton(parent=Acerca)
        self.btnSalirAcerca.setGeometry(QtCore.QRect(720, 470, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalirAcerca.setFont(font)
        self.btnSalirAcerca.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalirAcerca.setIcon(icon)
        self.btnSalirAcerca.setObjectName("btnSalirAcerca")

        self.retranslateUi(Acerca)
        QtCore.QMetaObject.connectSlotsByName(Acerca)

    def retranslateUi(self, Acerca):
        _translate = QtCore.QCoreApplication.translate
        Acerca.setWindowTitle(_translate("Acerca", "Form"))
        self.label.setText(_translate("Acerca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Descripción General:</span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">La Aplicación de Reservas de Laboratorios de la Universidad de Cuenca </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">es una herramienta diseñada para simplificar el proceso de reserva </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">de laboratorios, facilitando la coordinación  eficiente  y el uso óptimo </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">de los recursos disponibles en la universidad. </span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Esta aplicación fue desarrollada por </span><span style=\" font-size:10pt; font-weight:600;\">Yuzabeth Macas </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">en la materia de lenguajes de programación</span></p></body></html>"))
        self.btnSalirAcerca.setText(_translate("Acerca", "     SALIR"))
