# Form implementation generated from reading ui file 'Agendar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Agendar(object):
    def setupUi(self, Agendar):
        Agendar.setObjectName("Agendar")
        Agendar.resize(944, 758)
        Agendar.setStyleSheet("background-color: white;")
        self.label_7 = QtWidgets.QLabel(parent=Agendar)
        self.label_7.setGeometry(QtCore.QRect(40, 265, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=Agendar)
        self.label_8.setGeometry(QtCore.QRect(40, 130, 55, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.btnEliminarReservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnEliminarReservar.setGeometry(QtCore.QRect(490, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarReservar.setFont(font)
        self.btnEliminarReservar.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Macas_Yuzabeth_TrabajoFinal/Macas_Yuzabeth_TrabajoFinal/imagenes/eliminarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEliminarReservar.setIcon(icon)
        self.btnEliminarReservar.setObjectName("btnEliminarReservar")
        self.spinBoxReservar = QtWidgets.QSpinBox(parent=Agendar)
        self.spinBoxReservar.setGeometry(QtCore.QRect(170, 410, 42, 22))
        self.spinBoxReservar.setObjectName("spinBoxReservar")
        self.btnNuevoReservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnNuevoReservar.setGeometry(QtCore.QRect(190, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnNuevoReservar.setFont(font)
        self.btnNuevoReservar.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Macas_Yuzabeth_TrabajoFinal/Macas_Yuzabeth_TrabajoFinal/imagenes/agregarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNuevoReservar.setIcon(icon1)
        self.btnNuevoReservar.setObjectName("btnNuevoReservar")
        self.timeEditHora = QtWidgets.QTimeEdit(parent=Agendar)
        self.timeEditHora.setGeometry(QtCore.QRect(630, 400, 118, 31))
        self.timeEditHora.setObjectName("timeEditHora")
        self.btnListarReservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnListarReservar.setGeometry(QtCore.QRect(640, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnListarReservar.setFont(font)
        self.btnListarReservar.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/listarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnListarReservar.setIcon(icon2)
        self.btnListarReservar.setObjectName("btnListarReservar")
        self.txtNombreReservar = QtWidgets.QLineEdit(parent=Agendar)
        self.txtNombreReservar.setGeometry(QtCore.QRect(170, 190, 281, 31))
        self.txtNombreReservar.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtNombreReservar.setObjectName("txtNombreReservar")
        self.btnSalirRerservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnSalirRerservar.setGeometry(QtCore.QRect(790, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalirRerservar.setFont(font)
        self.btnSalirRerservar.setStyleSheet("\n"
"/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalirRerservar.setIcon(icon3)
        self.btnSalirRerservar.setObjectName("btnSalirRerservar")
        self.label_2 = QtWidgets.QLabel(parent=Agendar)
        self.label_2.setGeometry(QtCore.QRect(40, 195, 55, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBoxLabReservar = QtWidgets.QComboBox(parent=Agendar)
        self.comboBoxLabReservar.setGeometry(QtCore.QRect(170, 330, 281, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxLabReservar.setFont(font)
        self.comboBoxLabReservar.setStyleSheet("/* Estilo base del QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #B0B0B0; /* Borde del combobox */\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 1px 18px 1px 3px; /* Espaciado interno */\n"
"    min-width: 6em; /* Ancho mínimo del combobox */\n"
"    color: #333333; /* Color del texto */\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    selection-background-color: #D5DBDB; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del área editable del QComboBox */\n"
"QComboBox:editable {\n"
"    background: #FFFFFF; /* Fondo del área editable si es un combobox editable */\n"
"}\n"
"\n"
"/* Estilo del botón desplegable */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"    width: 20px; /* Ancho del botón desplegable */\n"
"    border-left: 1px solid #B0B0B0; /* Borde izquierdo del botón desplegable */\n"
"}\n"
"\n"
"\n"
"/* Estilo al pasar el ratón sobre el QComboBox */\n"
"QComboBox:hover {\n"
"    border: 1px solid #7D7D7D; /* Borde cuando el mouse pasa sobre el combobox */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón desplegable */\n"
"QComboBox::drop-down:hover {\n"
"    background: #BFC9CA; /* Fondo del botón desplegable cuando el mouse pasa sobre él */\n"
"}\n"
"\n"
"/* Estilo al seleccionar una opción en el QComboBox */\n"
"QComboBox::item:selected {\n"
"    background-color: #A9DEF9; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del texto en las opciones del QComboBox */\n"
"QComboBox::item {\n"
"    padding: 4px; /* Espaciado interno de las opciones */\n"
"}\n"
"\n"
"/* Estilo de la flecha cuando el QComboBox está desplegado */\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background: #EBEBEB; /* Fondo cuando el combobox está desplegado */\n"
"}\n"
"\n"
"")
        self.comboBoxLabReservar.setObjectName("comboBoxLabReservar")
        self.btnBuscarReservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnBuscarReservar.setGeometry(QtCore.QRect(40, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBuscarReservar.setFont(font)
        self.btnBuscarReservar.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/buscarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBuscarReservar.setIcon(icon4)
        self.btnBuscarReservar.setObjectName("btnBuscarReservar")
        self.btnModificarReservar = QtWidgets.QPushButton(parent=Agendar)
        self.btnModificarReservar.setGeometry(QtCore.QRect(340, 700, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnModificarReservar.setFont(font)
        self.btnModificarReservar.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/modificarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnModificarReservar.setIcon(icon5)
        self.btnModificarReservar.setObjectName("btnModificarReservar")
        self.label_5 = QtWidgets.QLabel(parent=Agendar)
        self.label_5.setGeometry(QtCore.QRect(40, 410, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabReservar = QtWidgets.QTableWidget(parent=Agendar)
        self.tabReservar.setGeometry(QtCore.QRect(40, 470, 871, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabReservar.setFont(font)
        self.tabReservar.setStyleSheet("QTableWidget {\n"
"    background-color: #F5F5F5; /* Color de fondo de la tabla */\n"
"    border: 1px solid #F0F3F4; /* Borde de la tabla */\n"
"    border-radius: 4px; /* Esquinas redondeadas de la tabla */\n"
"    padding: 4px; /* Espaciado interno de la tabla */\n"
"    gridline-color: #F0F3F4; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px; /* Espaciado interno de las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #ECF0F1; /* Color de fondo de la celda al pasar el ratón */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498DB; /* Color de fondo de la celda seleccionada */\n"
"    color: white; /* Color del texto en la celda seleccionada */\n"
"}                ")
        self.tabReservar.setObjectName("tabReservar")
        self.tabReservar.setColumnCount(0)
        self.tabReservar.setRowCount(0)
        self.txtApellidoReservar = QtWidgets.QLineEdit(parent=Agendar)
        self.txtApellidoReservar.setGeometry(QtCore.QRect(170, 260, 281, 31))
        self.txtApellidoReservar.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtApellidoReservar.setObjectName("txtApellidoReservar")
        self.label_3 = QtWidgets.QLabel(parent=Agendar)
        self.label_3.setGeometry(QtCore.QRect(40, 329, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtCedulaReservar = QtWidgets.QLineEdit(parent=Agendar)
        self.txtCedulaReservar.setGeometry(QtCore.QRect(170, 130, 281, 31))
        self.txtCedulaReservar.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtCedulaReservar.setObjectName("txtCedulaReservar")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Agendar)
        self.calendarWidget.setGeometry(QtCore.QRect(530, 140, 392, 236))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_6 = QtWidgets.QLabel(parent=Agendar)
        self.label_6.setGeometry(QtCore.QRect(530, 110, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(parent=Agendar)
        self.label_9.setGeometry(QtCore.QRect(540, 400, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lblTitulo = QtWidgets.QLabel(parent=Agendar)
        self.lblTitulo.setGeometry(QtCore.QRect(180, 20, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(Agendar)
        QtCore.QMetaObject.connectSlotsByName(Agendar)

    def retranslateUi(self, Agendar):
        _translate = QtCore.QCoreApplication.translate
        Agendar.setWindowTitle(_translate("Agendar", "Form"))
        self.label_7.setText(_translate("Agendar", "APELLIDO:"))
        self.label_8.setText(_translate("Agendar", "CÉDULA:"))
        self.btnEliminarReservar.setText(_translate("Agendar", "   ELIMINAR"))
        self.btnNuevoReservar.setText(_translate("Agendar", "RESERVAR"))
        self.btnListarReservar.setText(_translate("Agendar", "     LISTAR"))
        self.btnSalirRerservar.setText(_translate("Agendar", "     SALIR"))
        self.label_2.setText(_translate("Agendar", "NOMBRE:"))
        self.btnBuscarReservar.setText(_translate("Agendar", "      BUSCAR"))
        self.btnModificarReservar.setText(_translate("Agendar", " MODIFICAR"))
        self.label_5.setText(_translate("Agendar", "Nro. PERSONAS:"))
        self.label_3.setText(_translate("Agendar", "LABORATORIO:"))
        self.label_6.setText(_translate("Agendar", "FECHA:"))
        self.label_9.setText(_translate("Agendar", "HORA:"))
        self.lblTitulo.setText(_translate("Agendar", "<html><head/><body><p><span style=\" color:#00007f;\">RESERVAR LABORATORIO</span></p></body></html>"))
