# Form implementation generated from reading ui file 'Laboratorios.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Laboratorios(object):
    def setupUi(self, Laboratorios):
        Laboratorios.setObjectName("Laboratorios")
        Laboratorios.resize(889, 649)
        Laboratorios.setStyleSheet("background-color: white;")
        self.tabLaboratorio = QtWidgets.QTableWidget(parent=Laboratorios)
        self.tabLaboratorio.setGeometry(QtCore.QRect(30, 370, 821, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabLaboratorio.setFont(font)
        self.tabLaboratorio.setStyleSheet("QTableWidget {\n"
"    background-color: #F5F5F5; /* Color de fondo de la tabla */\n"
"    border: 1px solid #F0F3F4; /* Borde de la tabla */\n"
"    border-radius: 4px; /* Esquinas redondeadas de la tabla */\n"
"    padding: 4px; /* Espaciado interno de la tabla */\n"
"    gridline-color: #F0F3F4; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px; /* Espaciado interno de las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #ECF0F1; /* Color de fondo de la celda al pasar el ratón */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498DB; /* Color de fondo de la celda seleccionada */\n"
"    color: white; /* Color del texto en la celda seleccionada */\n"
"}")
        self.tabLaboratorio.setObjectName("tabLaboratorio")
        self.tabLaboratorio.setColumnCount(0)
        self.tabLaboratorio.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(parent=Laboratorios)
        self.label_2.setGeometry(QtCore.QRect(190, 140, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtNombreLaboratorio = QtWidgets.QLineEdit(parent=Laboratorios)
        self.txtNombreLaboratorio.setGeometry(QtCore.QRect(320, 130, 281, 31))
        self.txtNombreLaboratorio.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtNombreLaboratorio.setObjectName("txtNombreLaboratorio")
        self.txtTelefonoLaboratorio = QtWidgets.QLineEdit(parent=Laboratorios)
        self.txtTelefonoLaboratorio.setGeometry(QtCore.QRect(320, 310, 281, 31))
        self.txtTelefonoLaboratorio.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtTelefonoLaboratorio.setObjectName("txtTelefonoLaboratorio")
        self.btnListarLaboratorio = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnListarLaboratorio.setGeometry(QtCore.QRect(590, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnListarLaboratorio.setFont(font)
        self.btnListarLaboratorio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/listarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnListarLaboratorio.setIcon(icon)
        self.btnListarLaboratorio.setObjectName("btnListarLaboratorio")
        self.btnModificarLaboratorio = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnModificarLaboratorio.setGeometry(QtCore.QRect(310, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnModificarLaboratorio.setFont(font)
        self.btnModificarLaboratorio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/modificarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnModificarLaboratorio.setIcon(icon1)
        self.btnModificarLaboratorio.setObjectName("btnModificarLaboratorio")
        self.btnNuevoLaboratorio = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnNuevoLaboratorio.setGeometry(QtCore.QRect(30, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnNuevoLaboratorio.setFont(font)
        self.btnNuevoLaboratorio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/agregarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNuevoLaboratorio.setIcon(icon2)
        self.btnNuevoLaboratorio.setObjectName("btnNuevoLaboratorio")
        self.label_3 = QtWidgets.QLabel(parent=Laboratorios)
        self.label_3.setGeometry(QtCore.QRect(190, 190, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Laboratorios)
        self.label_4.setGeometry(QtCore.QRect(190, 250, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnEliminarLaboratorio = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnEliminarLaboratorio.setGeometry(QtCore.QRect(450, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarLaboratorio.setFont(font)
        self.btnEliminarLaboratorio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/eliminarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEliminarLaboratorio.setIcon(icon3)
        self.btnEliminarLaboratorio.setObjectName("btnEliminarLaboratorio")
        self.txtDireccionLaboratorio = QtWidgets.QLineEdit(parent=Laboratorios)
        self.txtDireccionLaboratorio.setGeometry(QtCore.QRect(320, 250, 281, 31))
        self.txtDireccionLaboratorio.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtDireccionLaboratorio.setObjectName("txtDireccionLaboratorio")
        self.txtApellidoLaboratorio = QtWidgets.QLineEdit(parent=Laboratorios)
        self.txtApellidoLaboratorio.setGeometry(QtCore.QRect(320, 190, 281, 31))
        self.txtApellidoLaboratorio.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtApellidoLaboratorio.setObjectName("txtApellidoLaboratorio")
        self.label_6 = QtWidgets.QLabel(parent=Laboratorios)
        self.label_6.setGeometry(QtCore.QRect(190, 320, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btnBuscarLaboratorio = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnBuscarLaboratorio.setGeometry(QtCore.QRect(170, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBuscarLaboratorio.setFont(font)
        self.btnBuscarLaboratorio.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/buscarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBuscarLaboratorio.setIcon(icon4)
        self.btnBuscarLaboratorio.setObjectName("btnBuscarLaboratorio")
        self.lblTitulo = QtWidgets.QLabel(parent=Laboratorios)
        self.lblTitulo.setGeometry(QtCore.QRect(130, 30, 631, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        self.btnSalirLaboratorios = QtWidgets.QPushButton(parent=Laboratorios)
        self.btnSalirLaboratorios.setGeometry(QtCore.QRect(730, 570, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalirLaboratorios.setFont(font)
        self.btnSalirLaboratorios.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalirLaboratorios.setIcon(icon5)
        self.btnSalirLaboratorios.setObjectName("btnSalirLaboratorios")

        self.retranslateUi(Laboratorios)
        QtCore.QMetaObject.connectSlotsByName(Laboratorios)

    def retranslateUi(self, Laboratorios):
        _translate = QtCore.QCoreApplication.translate
        Laboratorios.setWindowTitle(_translate("Laboratorios", "Form"))
        self.label_2.setText(_translate("Laboratorios", "NOMBRE:"))
        self.btnListarLaboratorio.setText(_translate("Laboratorios", "     LISTAR"))
        self.btnModificarLaboratorio.setText(_translate("Laboratorios", " MODIFICAR"))
        self.btnNuevoLaboratorio.setText(_translate("Laboratorios", "        NUEVO"))
        self.label_3.setText(_translate("Laboratorios", "ENCARGADO:"))
        self.label_4.setText(_translate("Laboratorios", "CAMPUS:"))
        self.btnEliminarLaboratorio.setText(_translate("Laboratorios", "   ELIMINAR"))
        self.label_6.setText(_translate("Laboratorios", "Nro. MÁQUINAS:"))
        self.btnBuscarLaboratorio.setText(_translate("Laboratorios", "      BUSCAR"))
        self.lblTitulo.setText(_translate("Laboratorios", "<html><head/><body><p><span style=\" color:#00007f;\">GESTIÓN DE LABORATORIOS</span></p></body></html>"))
        self.btnSalirLaboratorios.setText(_translate("Laboratorios", "     SALIR"))
