# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(792, 544)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Login.setFont(font)
        Login.setStyleSheet("background-color: white;\n"
"")
        self.lblEmail = QtWidgets.QLabel(parent=Login)
        self.lblEmail.setGeometry(QtCore.QRect(80, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail.setFont(font)
        self.lblEmail.setStyleSheet("background: transparent;\n"
"color: black;\n"
"")
        self.lblEmail.setObjectName("lblEmail")
        self.lblEmail_2 = QtWidgets.QLabel(parent=Login)
        self.lblEmail_2.setGeometry(QtCore.QRect(80, 250, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail_2.setFont(font)
        self.lblEmail_2.setStyleSheet("background: transparent;\n"
"color: black;\n"
"")
        self.lblEmail_2.setObjectName("lblEmail_2")
        self.btnIngresarLogin = QtWidgets.QPushButton(parent=Login)
        self.btnIngresarLogin.setGeometry(QtCore.QRect(150, 380, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnIngresarLogin.setFont(font)
        self.btnIngresarLogin.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        self.btnIngresarLogin.setObjectName("btnIngresarLogin")
        self.txtCorreoLogin = QtWidgets.QLineEdit(parent=Login)
        self.txtCorreoLogin.setGeometry(QtCore.QRect(80, 180, 271, 31))
        self.txtCorreoLogin.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #F5F5F5; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #F0F3F4; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"\n"
"\n"
"")
        self.txtCorreoLogin.setObjectName("txtCorreoLogin")
        self.txtContrasenaLogin = QtWidgets.QLineEdit(parent=Login)
        self.txtContrasenaLogin.setGeometry(QtCore.QRect(80, 300, 271, 31))
        self.txtContrasenaLogin.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #F5F5F5; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #F0F3F4; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"\n"
"\n"
"")
        self.txtContrasenaLogin.setObjectName("txtContrasenaLogin")
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(450, 40, 271, 151))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/ucuenca.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Login)
        self.label_2.setGeometry(QtCore.QRect(460, 210, 251, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/acceso.png"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.lblEmail.setText(_translate("Login", "<html><head/><body><p><span style=\" color:#000000;\">EMAIL:</span></p></body></html>"))
        self.lblEmail_2.setText(_translate("Login", "<html><head/><body><p><span style=\" color:#000000;\">CONTRASEÑA:</span></p></body></html>"))
        self.btnIngresarLogin.setText(_translate("Login", "INGRESAR"))
