    # Form implementation generated from reading ui file 'Reportes.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reportes(object):
    def setupUi(self, Reportes):
        Reportes.setObjectName("Reportes")
        Reportes.resize(962, 494)
        Reportes.setStyleSheet("background-color: #FFFAFA;")
        self.comboBoxReportes = QtWidgets.QComboBox(parent=Reportes)
        self.comboBoxReportes.setGeometry(QtCore.QRect(50, 111, 251, 31))
        self.comboBoxReportes.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBoxReportes.setStyleSheet("/* Estilo base del QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #B0B0B0; /* Borde del combobox */\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 1px 18px 1px 3px; /* Espaciado interno */\n"
"    min-width: 6em; /* Ancho mínimo del combobox */\n"
"    color: #333333; /* Color del texto */\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    selection-background-color: #D5DBDB; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del área editable del QComboBox */\n"
"QComboBox:editable {\n"
"    background: #FFFFFF; /* Fondo del área editable si es un combobox editable */\n"
"}\n"
"\n"
"/* Estilo del botón desplegable */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"    width: 20px; /* Ancho del botón desplegable */\n"
"    border-left: 1px solid #B0B0B0; /* Borde izquierdo del botón desplegable */\n"
"}\n"
"\n"
"\n"
"/* Estilo al pasar el ratón sobre el QComboBox */\n"
"QComboBox:hover {\n"
"    border: 1px solid #7D7D7D; /* Borde cuando el mouse pasa sobre el combobox */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón desplegable */\n"
"QComboBox::drop-down:hover {\n"
"    background: #BFC9CA; /* Fondo del botón desplegable cuando el mouse pasa sobre él */\n"
"}\n"
"\n"
"/* Estilo al seleccionar una opción en el QComboBox */\n"
"QComboBox::item:selected {\n"
"    background-color: #A9DEF9; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del texto en las opciones del QComboBox */\n"
"QComboBox::item {\n"
"    padding: 4px; /* Espaciado interno de las opciones */\n"
"}\n"
"\n"
"/* Estilo de la flecha cuando el QComboBox está desplegado */\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background: #EBEBEB; /* Fondo cuando el combobox está desplegado */\n"
"}\n"
"\n"
"")
        self.comboBoxReportes.setObjectName("comboBoxReportes")
        self.comboBoxReportes.addItem("")
        self.comboBoxReportes.addItem("")
        self.tabReportes = QtWidgets.QTableWidget(parent=Reportes)
        self.tabReportes.setGeometry(QtCore.QRect(50, 170, 881, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabReportes.setFont(font)
        self.tabReportes.setStyleSheet("QTableWidget {\n"
"    background-color: #F5F5F5; /* Color de fondo de la tabla */\n"
"    border: 1px solid #F0F3F4; /* Borde de la tabla */\n"
"    border-radius: 4px; /* Esquinas redondeadas de la tabla */\n"
"    padding: 4px; /* Espaciado interno de la tabla */\n"
"    gridline-color: #F0F3F4; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px; /* Espaciado interno de las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #ECF0F1; /* Color de fondo de la celda al pasar el ratón */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498DB; /* Color de fondo de la celda seleccionada */\n"
"    color: white; /* Color del texto en la celda seleccionada */\n"
"}                ")
        self.tabReportes.setObjectName("tabReportes")
        self.tabReportes.setColumnCount(0)
        self.tabReportes.setRowCount(0)
        self.btnSalirReportes = QtWidgets.QPushButton(parent=Reportes)
        self.btnSalirReportes.setGeometry(QtCore.QRect(810, 420, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalirReportes.setFont(font)
        self.btnSalirReportes.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalirReportes.setIcon(icon)
        self.btnSalirReportes.setObjectName("btnSalirReportes")
        self.lblTitulo = QtWidgets.QLabel(parent=Reportes)
        self.lblTitulo.setGeometry(QtCore.QRect(350, 10, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(Reportes)
        QtCore.QMetaObject.connectSlotsByName(Reportes)

    def retranslateUi(self, Reportes):
        _translate = QtCore.QCoreApplication.translate
        Reportes.setWindowTitle(_translate("Reportes", "Form"))
        self.comboBoxReportes.setItemText(0, _translate("Reportes", "Laboratorios reservados"))
        self.comboBoxReportes.setItemText(1, _translate("Reportes", "Laboratorio más reservado"))
        self.btnSalirReportes.setText(_translate("Reportes", "     SALIR"))
        self.lblTitulo.setText(_translate("Reportes", "<html><head/><body><p><span style=\" color:#00007f;\">REPORTES</span></p></body></html>"))
