# Form implementation generated from reading ui file 'Usuarios.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Usuarios(object):
    def setupUi(self, Usuarios):
        Usuarios.setObjectName("Usuarios")
        Usuarios.resize(929, 749)
        Usuarios.setStyleSheet("background-color: #FFFAFA ;")
        self.label_4 = QtWidgets.QLabel(parent=Usuarios)
        self.label_4.setGeometry(QtCore.QRect(180, 290, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnListarUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnListarUsuario.setGeometry(QtCore.QRect(630, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnListarUsuario.setFont(font)
        self.btnListarUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/listarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnListarUsuario.setIcon(icon)
        self.btnListarUsuario.setObjectName("btnListarUsuario")
        self.btnSalirUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnSalirUsuario.setGeometry(QtCore.QRect(780, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalirUsuario.setFont(font)
        self.btnSalirUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/salir.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSalirUsuario.setIcon(icon1)
        self.btnSalirUsuario.setObjectName("btnSalirUsuario")
        self.txtDireccionUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtDireccionUsuario.setGeometry(QtCore.QRect(290, 280, 281, 31))
        self.txtDireccionUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtDireccionUsuario.setObjectName("txtDireccionUsuario")
        self.txtCedulaUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtCedulaUsuario.setGeometry(QtCore.QRect(290, 100, 281, 31))
        self.txtCedulaUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtCedulaUsuario.setObjectName("txtCedulaUsuario")
        self.btnModificarUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnModificarUsuario.setGeometry(QtCore.QRect(330, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnModificarUsuario.setFont(font)
        self.btnModificarUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/modificarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnModificarUsuario.setIcon(icon2)
        self.btnModificarUsuario.setObjectName("btnModificarUsuario")
        self.txtTelefonoUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtTelefonoUsuario.setGeometry(QtCore.QRect(290, 340, 281, 31))
        self.txtTelefonoUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"\n"
"")
        self.txtTelefonoUsuario.setObjectName("txtTelefonoUsuario")
        self.label_2 = QtWidgets.QLabel(parent=Usuarios)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=Usuarios)
        self.label_6.setGeometry(QtCore.QRect(180, 410, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtNombreUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtNombreUsuario.setGeometry(QtCore.QRect(290, 160, 281, 31))
        self.txtNombreUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtNombreUsuario.setObjectName("txtNombreUsuario")
        self.tabUsuarios = QtWidgets.QTableWidget(parent=Usuarios)
        self.tabUsuarios.setGeometry(QtCore.QRect(30, 460, 871, 201))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabUsuarios.setFont(font)
        self.tabUsuarios.setStyleSheet("QTableWidget {\n"
"    background-color: #F5F5F5; /* Color de fondo de la tabla */\n"
"    border: 1px solid #F0F3F4; /* Borde de la tabla */\n"
"    border-radius: 4px; /* Esquinas redondeadas de la tabla */\n"
"    padding: 4px; /* Espaciado interno de la tabla */\n"
"    gridline-color: #F0F3F4; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px; /* Espaciado interno de las celdas */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #ECF0F1; /* Color de fondo de la celda al pasar el ratón */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3498DB; /* Color de fondo de la celda seleccionada */\n"
"    color: white; /* Color del texto en la celda seleccionada */\n"
"}                ")
        self.tabUsuarios.setObjectName("tabUsuarios")
        self.tabUsuarios.setColumnCount(0)
        self.tabUsuarios.setRowCount(0)
        self.txtCorreoUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtCorreoUsuario.setGeometry(QtCore.QRect(290, 400, 281, 31))
        self.txtCorreoUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtCorreoUsuario.setObjectName("txtCorreoUsuario")
        self.label_3 = QtWidgets.QLabel(parent=Usuarios)
        self.label_3.setGeometry(QtCore.QRect(180, 230, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnEliminarUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnEliminarUsuario.setGeometry(QtCore.QRect(480, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminarUsuario.setFont(font)
        self.btnEliminarUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/eliminarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnEliminarUsuario.setIcon(icon3)
        self.btnEliminarUsuario.setObjectName("btnEliminarUsuario")
        self.btnNuevoUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnNuevoUsuario.setGeometry(QtCore.QRect(30, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnNuevoUsuario.setFont(font)
        self.btnNuevoUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/agregarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNuevoUsuario.setIcon(icon4)
        self.btnNuevoUsuario.setObjectName("btnNuevoUsuario")
        self.btnBuscarUsuario = QtWidgets.QPushButton(parent=Usuarios)
        self.btnBuscarUsuario.setGeometry(QtCore.QRect(180, 690, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnBuscarUsuario.setFont(font)
        self.btnBuscarUsuario.setStyleSheet("/* Estilo base del botón */\n"
"QPushButton {\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    color: black; /* Color del texto */\n"
"    border: 2px solid #E5E7E9; /* Borde del botón */\n"
"    border-radius: 4px; /* Esquinas redondeadas */\n"
"    padding: 8px 16px; /* Espaciado interno */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón */\n"
"QPushButton:hover {\n"
"    background-color: #D5DBDB; /* Nuevo color de fondo al pasar el ratón */\n"
"    border: 2px solid #CCD1D1; /* Nuevo borde al pasar el ratón */\n"
"    color: black; /* Nuevo color del texto al pasar el ratón */\n"
"}\n"
"\n"
"/* Estilo al hacer clic en el botón */\n"
"QPushButton:pressed {\n"
"    background-color: #BFC9CA; /* Nuevo color de fondo al hacer clic */\n"
"    border: 2px solid #BFC9CA; /* Nuevo borde al hacer clic */\n"
"    color: black; /* Nuevo color del texto al hacer clic */\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/buscarUsuario.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnBuscarUsuario.setIcon(icon5)
        self.btnBuscarUsuario.setObjectName("btnBuscarUsuario")
        self.label_5 = QtWidgets.QLabel(parent=Usuarios)
        self.label_5.setGeometry(QtCore.QRect(180, 350, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txtApellidoUsuario = QtWidgets.QLineEdit(parent=Usuarios)
        self.txtApellidoUsuario.setGeometry(QtCore.QRect(290, 220, 281, 31))
        self.txtApellidoUsuario.setStyleSheet("QLineEdit:enabled {\n"
"    background-color: #E5E7E9; /* Color de fondo cuando está habilitado */\n"
"    border: 1px solid #E5E7E9; /* Borde del cuadro de texto cuando está habilitado */\n"
"    border-radius: 4px; /* Esquinas redondeadas cuando está habilitado */\n"
"    padding: 4px; /* Espaciado interno cuando está habilitado */\n"
"}\n"
"\n"
"QLineEdit:enabled:hover {\n"
"    background-color: #ECF0F1; /* Cambiar el color de fondo al pasar el ratón */\n"
"}\n"
"\n"
"QLineEdit:enabled:focus {\n"
"    border: 2px solid #D0D3D4 /* Cambiar el borde al obtener el foco */\n"
"}\n"
"")
        self.txtApellidoUsuario.setObjectName("txtApellidoUsuario")
        self.label_8 = QtWidgets.QLabel(parent=Usuarios)
        self.label_8.setGeometry(QtCore.QRect(180, 110, 55, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBoxDocEst = QtWidgets.QComboBox(parent=Usuarios)
        self.comboBoxDocEst.setGeometry(QtCore.QRect(630, 100, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxDocEst.setFont(font)
        self.comboBoxDocEst.setStyleSheet("/* Estilo base del QComboBox */\n"
"QComboBox {\n"
"    border: 1px solid #B0B0B0; /* Borde del combobox */\n"
"    border-radius: 5px; /* Esquinas redondeadas */\n"
"    padding: 1px 18px 1px 3px; /* Espaciado interno */\n"
"    min-width: 6em; /* Ancho mínimo del combobox */\n"
"    color: #333333; /* Color del texto */\n"
"    background-color: #E5E7E9; /* Color de fondo */\n"
"    selection-background-color: #D5DBDB; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del área editable del QComboBox */\n"
"QComboBox:editable {\n"
"    background: #FFFFFF; /* Fondo del área editable si es un combobox editable */\n"
"}\n"
"\n"
"/* Estilo del botón desplegable */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"    width: 20px; /* Ancho del botón desplegable */\n"
"    border-left: 1px solid #B0B0B0; /* Borde izquierdo del botón desplegable */\n"
"}\n"
"\n"
"\n"
"/* Estilo al pasar el ratón sobre el QComboBox */\n"
"QComboBox:hover {\n"
"    border: 1px solid #7D7D7D; /* Borde cuando el mouse pasa sobre el combobox */\n"
"}\n"
"\n"
"/* Estilo al pasar el ratón sobre el botón desplegable */\n"
"QComboBox::drop-down:hover {\n"
"    background: #BFC9CA; /* Fondo del botón desplegable cuando el mouse pasa sobre él */\n"
"}\n"
"\n"
"/* Estilo al seleccionar una opción en el QComboBox */\n"
"QComboBox::item:selected {\n"
"    background-color: #A9DEF9; /* Color de fondo cuando está seleccionado */\n"
"}\n"
"\n"
"/* Estilo del texto en las opciones del QComboBox */\n"
"QComboBox::item {\n"
"    padding: 4px; /* Espaciado interno de las opciones */\n"
"}\n"
"\n"
"/* Estilo de la flecha cuando el QComboBox está desplegado */\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background: #EBEBEB; /* Fondo cuando el combobox está desplegado */\n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxDocEst.setObjectName("comboBoxDocEst")
        self.comboBoxDocEst.addItem("")
        self.comboBoxDocEst.addItem("")
        self.lblTitulo = QtWidgets.QLabel(parent=Usuarios)
        self.lblTitulo.setGeometry(QtCore.QRect(220, 10, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")

        self.retranslateUi(Usuarios)
        QtCore.QMetaObject.connectSlotsByName(Usuarios)

    def retranslateUi(self, Usuarios):
        _translate = QtCore.QCoreApplication.translate
        Usuarios.setWindowTitle(_translate("Usuarios", "Form"))
        self.label_4.setText(_translate("Usuarios", "CONTRASEÑA:"))
        self.btnListarUsuario.setText(_translate("Usuarios", "     LISTAR"))
        self.btnSalirUsuario.setText(_translate("Usuarios", "     SALIR"))
        self.btnModificarUsuario.setText(_translate("Usuarios", " MODIFICAR"))
        self.label_2.setText(_translate("Usuarios", "NOMBRE:"))
        self.label_6.setText(_translate("Usuarios", "CORREO:"))
        self.label_3.setText(_translate("Usuarios", "APELLIDO:"))
        self.btnEliminarUsuario.setText(_translate("Usuarios", "   ELIMINAR"))
        self.btnNuevoUsuario.setText(_translate("Usuarios", "        NUEVO"))
        self.btnBuscarUsuario.setText(_translate("Usuarios", "      BUSCAR"))
        self.label_5.setText(_translate("Usuarios", "TELÉFONO:"))
        self.label_8.setText(_translate("Usuarios", "CÉDULA:"))
        self.comboBoxDocEst.setItemText(0, _translate("Usuarios", "Docente"))
        self.comboBoxDocEst.setItemText(1, _translate("Usuarios", "Estudiante"))
        self.lblTitulo.setText(_translate("Usuarios", "<html><head/><body><p><span style=\" color:#00007f;\">GESTIÓN DE USUARIOS</span></p></body></html>"))
