# Form implementation generated from reading ui file 'VentanaPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 795)
        MainWindow.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFondo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFondo.setGeometry(QtCore.QRect(0, 0, 1080, 681))
        self.lblFondo.setText("")
        self.lblFondo.setPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/balzay.jpg"))
        self.lblFondo.setObjectName("lblFondo")
        self.lblTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(410, 680, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setObjectName("lblTitulo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(parent=self.menubar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../TrabajoFinal/imagenes/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menumenu.setIcon(icon)
        self.menumenu.setObjectName("menumenu")
        self.menuAdministrador = QtWidgets.QMenu(parent=self.menumenu)
        self.menuAdministrador.setObjectName("menuAdministrador")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionReservervar = QtGui.QAction(parent=MainWindow)
        self.actionReservervar.setObjectName("actionReservervar")
        self.actionAcerca_de = QtGui.QAction(parent=MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionUsuarios = QtGui.QAction(parent=MainWindow)
        self.actionUsuarios.setObjectName("actionUsuarios")
        self.actionLaboratorios = QtGui.QAction(parent=MainWindow)
        self.actionLaboratorios.setObjectName("actionLaboratorios")
        self.actionSolicitudes = QtGui.QAction(parent=MainWindow)
        self.actionSolicitudes.setObjectName("actionSolicitudes")
        self.actionReportes = QtGui.QAction(parent=MainWindow)
        self.actionReportes.setObjectName("actionReportes")
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuAdministrador.addAction(self.actionUsuarios)
        self.menuAdministrador.addAction(self.actionLaboratorios)
        self.menuAdministrador.addAction(self.actionReportes)
        self.menumenu.addAction(self.menuAdministrador.menuAction())
        self.menumenu.addAction(self.actionReservervar)
        self.menumenu.addAction(self.actionAcerca_de)
        self.menumenu.addSeparator()
        self.menumenu.addAction(self.actionSalir)
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitulo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#00007f;\">RESERVA DE LABORATORIOS</span></p></body></html>"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.menuAdministrador.setTitle(_translate("MainWindow", "Administrador"))
        self.actionReservervar.setText(_translate("MainWindow", "Reservar"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))
        self.actionUsuarios.setText(_translate("MainWindow", "Usuarios"))
        self.actionLaboratorios.setText(_translate("MainWindow", "Laboratorios"))
        self.actionSolicitudes.setText(_translate("MainWindow", "Solicitudes"))
        self.actionReportes.setText(_translate("MainWindow", "Reportes"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
